I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 521, in script
    scene nure with Disssolve (.8)
  File "game/script.rpy", line 521, in <module>
    scene nure with Disssolve (.8)
NameError: name 'Disssolve' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 521, in script
    scene nure with Disssolve (.8)
  File "C:\Users\Daria\Downloads\renpy-7.0.0-sdk\renpy\ast.py", line 1371, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\Daria\Downloads\renpy-7.0.0-sdk\renpy\python.py", line 1961, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Daria\Downloads\renpy-7.0.0-sdk\renpy\python.py", line 1954, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 521, in <module>
    scene nure with Disssolve (.8)
NameError: name 'Disssolve' is not defined

Windows-8-6.2.9200
Ren'Py 7.2.2.491
studentnure 1.0
Fri Nov 22 00:54:10 2019
